#!/usr/bin/env python3
"""Generate standard SPECT QA phantom fragments for OpenTOPAS-SPECT.

Geometry is traceable to manufacturer datasheets (Data Spectrum) and the NEMA/IEC standards;
see research/knowledge/spect-qa-phantom-geometry/ for the provenance and reliability grades.
No dimension here is invented. Materials use Geant4 NIST names (PMMA = G4_PLEXIGLASS).

Each fragment is an IncludeFile: it defines Ge/* geometry (Parent World) and So/* sources. The
example deck adds World, physics, a collimator+detector (a systems/ preset) and a scorer, and is
run from its own folder so the `../../` include resolves.

Usage:
  python3 tools/make_qa_phantom.py jaszczak [--model deluxe|ultradeluxe|standard|benchmark]
  python3 tools/make_qa_phantom.py nema-iec [--ratio 4.0]
  python3 tools/make_qa_phantom.py resolution [--in-water]
  python3 tools/make_qa_phantom.py all         # regenerate the shipped fragments
"""
import argparse, math, os

PMMA = "G4_PLEXIGLASS"        # NIST PMMA / acrylic / Lucite, 1.19 g/cm3
WATER = "G4_WATER"
TC99M = 140.5                 # keV, the standard QA isotope photopeak

# --- Jaszczak ECT rod/sphere diameters by model (Data Spectrum datasheet, Reliability A) ---
JASZ = {
    "ultradeluxe": ([3.2, 4.8, 6.4, 7.9, 9.5, 11.1], [9.5, 12.7, 15.9, 19.1, 25.4, 31.8]),
    "deluxe":      ([4.8, 6.4, 7.9, 9.5, 11.1, 12.7], [9.5, 12.7, 15.9, 19.1, 25.4, 31.8]),
    "standard":    ([6.4, 7.9, 9.5, 11.1, 12.7, 19.1], [12.7, 15.9, 19.1, 25.4, 31.8, 38.1]),
    "benchmark":   ([9.5, 11.1, 12.7, 15.9, 19.1, 25.4], [12.7, 15.9, 19.1, 25.4, 31.8, 38.1]),
}


def jaszczak(model="deluxe", energy=TC99M, base_histories=200000):
    rod_d, sph_d = JASZ[model]
    R_water, HL_water = 108.0, 93.0          # 216 mm ID, 186 mm inside height
    R_active = 98.0                          # rods stay 10 mm inside the water wall
    rod_hz = 44.0                            # 88 mm rod height / 2
    z_rods = -HL_water + rod_hz              # rod insert in the lower axial section
    z_sph = -HL_water + 127.0                # sphere centers 127 mm from base

    # hex-packed rods per 60-deg sector, pitch = 2*diameter; greedy reject any overlap
    accepted = []  # (x, y, d)
    for s in range(6):
        d = rod_d[s]; p = 2.0 * d; r = d / 2.0
        dx = p; dy = p * math.sqrt(3) / 2.0
        ny = int(R_active * 2 / dy) + 2; nx = int(R_active * 2 / dx) + 2
        for iy in range(-ny, ny + 1):
            y = iy * dy; xoff = (p / 2.0) if (iy % 2) else 0.0
            for ix in range(-nx, nx + 1):
                x = ix * dx + xoff
                rr = math.hypot(x, y)
                if rr < 9.0 or rr + r > R_active:
                    continue
                ang = math.degrees(math.atan2(y, x)) % 360.0
                if not (s * 60.0 + 2.0 <= ang < (s + 1) * 60.0 - 2.0):
                    continue          # small guard band between sectors
                if all(math.hypot(x - ax, y - ay) > r + ad / 2.0 + 0.5 for ax, ay, ad in accepted):
                    accepted.append((x, y, d))

    L = []
    L.append(f"# Jaszczak ECT phantom ({model}), tomographic QA: uniformity + spatial resolution (cold")
    L.append("# rods) + contrast (cold spheres) in one water-filled acrylic cylinder. Geometry from the")
    L.append("# Data Spectrum datasheet (see research/knowledge/spect-qa-phantom-geometry/). PMMA cylinder")
    L.append("# 216 mm ID x 186 mm, 3.2 mm wall; cold PMMA rods (pitch = 2x diameter, 88 mm tall) and cold")
    L.append("# PMMA spheres sit in a uniformly-active water background, so they read as cold voids.")
    L.append("#")
    L.append("# IncludeFile fragment: defines Ge/Jasz* (Parent World) + one background Volumetric source.")
    L.append(f"# Emits {energy:g} keV gamma (Tc-99m). Edit So/JaszBkg/VolumetricEnergy for other isotopes.")
    L.append(f"# Generated by tools/make_qa_phantom.py ({len(accepted)} rods).")
    L.append("")
    L.append('s:Ge/JaszShell/Type = "TsCylinder"')
    L.append('s:Ge/JaszShell/Parent = "World"')
    L.append(f's:Ge/JaszShell/Material = "{PMMA}"')
    L.append(f"d:Ge/JaszShell/RMax = {R_water + 3.2:.1f} mm")
    L.append(f"d:Ge/JaszShell/HL = {HL_water + 3.2:.1f} mm")
    L.append('s:Ge/JaszShell/Color = "grey"')
    L.append('s:Ge/JaszShell/DrawingStyle = "WireFrame"')
    L.append('s:Ge/JaszWater/Type = "TsCylinder"')
    L.append('s:Ge/JaszWater/Parent = "JaszShell"')
    L.append(f's:Ge/JaszWater/Material = "{WATER}"')
    L.append(f"d:Ge/JaszWater/RMax = {R_water:.1f} mm")
    L.append(f"d:Ge/JaszWater/HL = {HL_water:.1f} mm")
    L.append('s:Ge/JaszWater/Color = "blue"')
    L.append("")
    L.append("# --- cold rods (6 sectors, one diameter each; hex lattice, pitch = 2x diameter) ---")
    for i, (x, y, d) in enumerate(accepted):
        L.append(f's:Ge/Rod{i}/Type = "TsCylinder"')
        L.append(f's:Ge/Rod{i}/Parent = "JaszWater"')
        L.append(f's:Ge/Rod{i}/Material = "{PMMA}"')
        L.append(f"d:Ge/Rod{i}/RMax = {d/2.0:.2f} mm")
        L.append(f"d:Ge/Rod{i}/HL = {rod_hz:.1f} mm")
        L.append(f"d:Ge/Rod{i}/TransX = {x:.2f} mm")
        L.append(f"d:Ge/Rod{i}/TransY = {y:.2f} mm")
        L.append(f"d:Ge/Rod{i}/TransZ = {z_rods:.2f} mm")
    L.append("")
    L.append("# --- cold spheres (6, on a circle in the upper section) ---")
    for i, d in enumerate(sph_d):
        ang = math.radians(i * 60.0 + 30.0)
        L.append(f's:Ge/Sph{i}/Type = "TsSphere"')
        L.append(f's:Ge/Sph{i}/Parent = "JaszWater"')
        L.append(f's:Ge/Sph{i}/Material = "{PMMA}"')
        L.append(f"d:Ge/Sph{i}/RMax = {d/2.0:.2f} mm")
        L.append(f"d:Ge/Sph{i}/TransX = {58.0*math.cos(ang):.2f} mm")
        L.append(f"d:Ge/Sph{i}/TransY = {58.0*math.sin(ang):.2f} mm")
        L.append(f"d:Ge/Sph{i}/TransZ = {z_sph:.2f} mm")
    L.append("")
    L.append("# --- background activity: uniform in the water (rods/spheres are cold PMMA voids) ---")
    L.append('s:So/JaszBkg/Type = "Volumetric"')
    L.append('s:So/JaszBkg/Component = "JaszWater"')
    L.append('s:So/JaszBkg/VolumetricParticle = "gamma"')
    L.append(f"d:So/JaszBkg/VolumetricEnergy = {energy:g} keV")
    L.append(f's:So/JaszBkg/ActiveMaterial = "{WATER}"')
    L.append('b:So/JaszBkg/RecursivelyIncludeChildren = "False"')
    L.append(f"i:So/JaszBkg/NumberOfHistoriesInRun = {base_histories}")
    L.append("")
    return "\n".join(L)


def nema_iec(ratio=4.0, energy=TC99M, bkg_histories=100000):
    # interior lateral 290 (x), AP 221 (y), length 193 (z); wall 3.2 mm
    hx, hy, hz = 145.0, 110.5, 96.5
    spheres = [10.0, 13.0, 17.0, 22.0, 28.0, 37.0]
    z_sph = hz - 70.0                 # centers 70 mm from the lid (top)
    R_ring = 57.2                     # standard sphere-center circle
    L = []
    L.append("# NEMA IEC body phantom (IEC 61675-1 / NEMA NU 2-2018), contrast-recovery QA. Six hot")
    L.append("# fillable spheres (10-37 mm) in a warm body, with a cold low-density lung insert. Geometry")
    L.append("# from the Data Spectrum datasheet (research/knowledge/spect-qa-phantom-geometry/).")
    L.append(f"# Sphere:background activity-concentration ratio = {ratio:g}:1 (edit the histories to change it).")
    L.append("#")
    L.append("# IncludeFile fragment: Ge/IEC* (Parent World) + a warm-background source and one hot source")
    L.append("# per sphere. Sphere walls (~1 mm PMMA) are not modeled (assumption; small attenuation).")
    L.append(f"# Emits {energy:g} keV gamma (Tc-99m). Generated by tools/make_qa_phantom.py.")
    L.append("")
    L.append("# Low-density lung foam: polystyrene at 0.3 g/cm3 (styrofoam+water average, NEMA NU 2).")
    L.append('sv:Ma/Styrofoam/Components = 2 "Carbon" "Hydrogen"')
    L.append("uv:Ma/Styrofoam/Fractions = 2 0.9226 0.0774")
    L.append("d:Ma/Styrofoam/Density = 0.3 g/cm3")
    L.append("")
    L.append('s:Ge/IECShell/Type = "G4EllipticalTube"')
    L.append('s:Ge/IECShell/Parent = "World"')
    L.append(f's:Ge/IECShell/Material = "{PMMA}"')
    L.append(f"d:Ge/IECShell/HLX = {hx+3.2:.1f} mm\nd:Ge/IECShell/HLY = {hy+3.2:.1f} mm\nd:Ge/IECShell/HLZ = {hz+3.2:.1f} mm")
    L.append('s:Ge/IECShell/Color = "grey"\ns:Ge/IECShell/DrawingStyle = "WireFrame"')
    L.append('s:Ge/IECWater/Type = "G4EllipticalTube"')
    L.append('s:Ge/IECWater/Parent = "IECShell"')
    L.append(f's:Ge/IECWater/Material = "{WATER}"')
    L.append(f"d:Ge/IECWater/HLX = {hx:.1f} mm\nd:Ge/IECWater/HLY = {hy:.1f} mm\nd:Ge/IECWater/HLZ = {hz:.1f} mm")
    L.append('s:Ge/IECWater/Color = "lightblue"')
    L.append("")
    L.append("# cold lung insert (45 mm ID foam cylinder, on axis)")
    L.append('s:Ge/IECLung/Type = "TsCylinder"')
    L.append('s:Ge/IECLung/Parent = "IECWater"')
    L.append('s:Ge/IECLung/Material = "Styrofoam"')
    L.append(f"d:Ge/IECLung/RMax = 22.5 mm\nd:Ge/IECLung/HL = 92.5 mm")
    L.append('s:Ge/IECLung/Color = "white"')
    L.append("")
    L.append("# six hot spheres")
    for i, d in enumerate(spheres):
        ang = math.radians(i * 60.0)
        L.append(f's:Ge/Sph{i}/Type = "TsSphere"')
        L.append(f's:Ge/Sph{i}/Parent = "IECWater"')
        L.append(f's:Ge/Sph{i}/Material = "{WATER}"')
        L.append(f"d:Ge/Sph{i}/RMax = {d/2.0:.2f} mm")
        L.append(f"d:Ge/Sph{i}/TransX = {R_ring*math.cos(ang):.2f} mm")
        L.append(f"d:Ge/Sph{i}/TransY = {R_ring*math.sin(ang):.2f} mm")
        L.append(f"d:Ge/Sph{i}/TransZ = {z_sph:.2f} mm")
        L.append(f's:Ge/Sph{i}/Color = "red"')
    L.append("")
    L.append("# warm background (children excluded so lung stays cold and spheres get their own source)")
    L.append('s:So/IECBkg/Type = "Volumetric"')
    L.append('s:So/IECBkg/Component = "IECWater"')
    L.append('s:So/IECBkg/VolumetricParticle = "gamma"')
    L.append(f"d:So/IECBkg/VolumetricEnergy = {energy:g} keV")
    L.append(f's:So/IECBkg/ActiveMaterial = "{WATER}"')
    L.append('b:So/IECBkg/RecursivelyIncludeChildren = "False"')
    L.append(f"i:So/IECBkg/NumberOfHistoriesInRun = {bkg_histories}")
    L.append("")
    L.append(f"# hot spheres: histories = ratio ({ratio:g}) x background-concentration x sphere volume, so")
    L.append("# the sphere:background CONCENTRATION ratio is exact. Small spheres get few counts by design")
    L.append("# (that is why they are hard to recover); scale all histories up together for real statistics.")
    bkg_conc = bkg_histories / (math.pi * hx * hy * 2.0 * hz)   # elliptical-tube background concentration
    for i, d in enumerate(spheres):
        vol = 4.0/3.0 * math.pi * (d/2.0)**3
        n = max(1, round(ratio * bkg_conc * vol))
        L.append(f's:So/Sph{i}Src/Type = "Volumetric"')
        L.append(f's:So/Sph{i}Src/Component = "Sph{i}"')
        L.append(f's:So/Sph{i}Src/VolumetricParticle = "gamma"')
        L.append(f"d:So/Sph{i}Src/VolumetricEnergy = {energy:g} keV")
        L.append(f's:So/Sph{i}Src/ActiveMaterial = "{WATER}"')
        L.append(f"i:So/Sph{i}Src/NumberOfHistoriesInRun = {n}")
    L.append("")
    return "\n".join(L)


def resolution(in_water=False, energy=TC99M, histories=200000):
    L = []
    L.append("# NEMA NU-1-2018 spatial-resolution sources: three thin line sources (capillary bore < 1 mm)")
    L.append("# along the axis, at 0 and +/-75 mm (7.5 cm NEMA spacing). Reconstruct and fit the FWHM per")
    L.append("# source for radial/tangential resolution. Geometry per NEMA NU-1-2018.")
    L.append(f"#{'  In a 20 cm water cylinder (with scatter).' if in_water else '  In air (without scatter).'}")
    L.append("# IncludeFile fragment: Ge/Line* (Parent World) + one line Volumetric source each.")
    L.append(f"# Emits {energy:g} keV gamma (Tc-99m). Generated by tools/make_qa_phantom.py.")
    L.append("")
    if in_water:
        L.append('s:Ge/ScatterMedium/Type = "TsCylinder"')
        L.append('s:Ge/ScatterMedium/Parent = "World"')
        L.append(f's:Ge/ScatterMedium/Material = "{WATER}"')
        L.append("d:Ge/ScatterMedium/RMax = 100. mm\nd:Ge/ScatterMedium/HL = 100. mm")
        L.append('s:Ge/ScatterMedium/Color = "blue"\ns:Ge/ScatterMedium/DrawingStyle = "WireFrame"')
        parent = "ScatterMedium"
    else:
        parent = "World"
    L.append("")
    for i, x in enumerate((-75.0, 0.0, 75.0)):
        L.append(f's:Ge/Line{i}/Type = "TsCylinder"')
        L.append(f's:Ge/Line{i}/Parent = "{parent}"')
        L.append(f's:Ge/Line{i}/Material = "{WATER}"')
        L.append(f"d:Ge/Line{i}/RMax = 0.4 mm\nd:Ge/Line{i}/HL = 95. mm")
        L.append(f"d:Ge/Line{i}/TransX = {x:.1f} mm")
        L.append(f's:Ge/Line{i}/Color = "red"')
        L.append(f's:So/Line{i}Src/Type = "Volumetric"')
        L.append(f's:So/Line{i}Src/Component = "Line{i}"')
        L.append(f's:So/Line{i}Src/VolumetricParticle = "gamma"')
        L.append(f"d:So/Line{i}Src/VolumetricEnergy = {energy:g} keV")
        L.append(f's:So/Line{i}Src/ActiveMaterial = "{WATER}"')
        L.append(f"i:So/Line{i}Src/NumberOfHistoriesInRun = {histories}")
        L.append("")
    return "\n".join(L)


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    qa = os.path.join(here, "phantoms", "qa"); os.makedirs(qa, exist_ok=True)
    ap = argparse.ArgumentParser()
    ap.add_argument("kind", choices=["jaszczak", "nema-iec", "resolution", "all"])
    ap.add_argument("--model", default="deluxe", choices=list(JASZ))
    ap.add_argument("--ratio", type=float, default=4.0)
    ap.add_argument("--in-water", action="store_true")
    a = ap.parse_args()
    if a.kind in ("jaszczak", "all"):
        open(os.path.join(qa, "jaszczak_deluxe.txt"), "w").write(jaszczak("deluxe"))
        print("wrote phantoms/qa/jaszczak_deluxe.txt")
    if a.kind in ("nema-iec", "all"):
        open(os.path.join(qa, "nema_iec_body.txt"), "w").write(nema_iec(a.ratio))
        print("wrote phantoms/qa/nema_iec_body.txt")
    if a.kind in ("resolution", "all"):
        open(os.path.join(qa, "resolution_sources.txt"), "w").write(resolution(a.in_water))
        print("wrote phantoms/qa/resolution_sources.txt")


if __name__ == "__main__":
    main()
